### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yuyuko233** [4n4nk3/HikPwn#2]
File "E:\HikPwn-master\hikpwn.py", line 321
    HOSTS: Dict[str, HikDevice] = {**DETECTED_PASSIVE, **DETECTED_ACTIVE}
    ^
SyntaxError: annotated name 'HOSTS' can't be global
------------------------------------------------------------------
Please fix this error

**Comment by littleheary** [comment]
同问，我也是这个报错。

**Comment by 4n4nk3** [comment]
Thank you for your feedback. Unfortunately I don't get such error in Python 3.8.
Can you please tell me which version of Python are you using?

Anyway you can try to change that line from:
`HOSTS: Dict[str, HikDevice] = {**DETECTED_PASSIVE, **DETECTED_ACTIVE}`
To:
`HOSTS = {**DETECTED_PASSIVE, **DETECTED_ACTIVE}`

Please let me know if this fixes it for you so that i can eventually modify it in master branch

**Comment by yuyuko233** [comment]
> Thank you for your feedback. Unfortunately I don't get such error in Python 3.8.
> Can you please tell me which version of Python are you using?
> 
> Anyway you can try to change that line from:
> `HOSTS: Dict[str, HikDevice] = {**DETECTED_PASSIVE, **DETECTED_ACTIVE}`
> To:
> `HOSTS = {**DETECTED_PASSIVE, **DETECTED_ACTIVE}`
> 
> Please let me know if this fixes it for you so that i can eventually modify it in master branch


I am using Python 3.6.6

**Comment by 4n4nk3** [comment]
Thank you
